export * as Icons from "./_icons";
export * as Layouts from "./_layouts";
export * as Sections from "./_sections";
export { default as Content } from "./Content";
export { default as Footer } from "./Footer";
export { default as Head } from "./Head";
export { default as Loader } from "./Loader";
export { default as Project } from "./Project";
export { default as Service } from "./Service";
export { default as Skill } from "./Skill";